---
- hosts: all

  vars:
    pg_version: 9.3
    mysql_version: 5.6
    phantomjs_version: 1.9.7
    elasticsearch_version: 1.2.1

    services_onboot:
      - postgresql
      - redis-server
      - mysql-server
      - xvfb

    ruby_default_version: 2.0.0
    nodejs_default_version: 0.10
    java_default_version: java-1.7.0-openjdk-amd64

    java_packages:
      - openjdk-7-jdk
      - icedtea-7-plugin

    java_ora_versions:
      - oracle-java7-installer
      - oracle-java8-installer

    installed_packages:
      - tzdata
      - git-core
      - mercurial
      - bzr
      - patch
      - bison
      - curl
      - build-essential
      - libcurl4-openssl-dev
      - libssl-dev
      - libxml2-dev
      - libxslt1-dev
      - sqlite3
      - libsqlite3-dev
      - autoconf
      - libyaml-dev
      - libreadline6
      - libreadline6-dev
      - zlib1g
      - zlib1g-dev
      - imagemagick
      - libmagickwand-dev
      - cmake
      - libicu-dev
      - zip
      - unzip
      - libmemcached-dev
      - augeas-tools

  roles:
    - bootstrap
    - env

    - qt
    - xvfb
    - firefox

    - ruby
    - python
    - nodejs
    - java
    - sbt
    - lein

    - phantomjs

    - postgresql
    - redis
    - memcached
    - mysql
    - rabbitmq
    - elasticsearch
    - mongodb
    - sphinxsearch

    - services

